### ISSUE TITLE
Adib in the Lazyman Neovim Configuration Manager

### ISSUE THREAD

**Issue by doctorfree** [adibhanna/nvim#2]
I've created a Neovim Configuration Manager that supports easy installation and initialization of multiple Neovim configurations using the `NVIM_APPNAME` environment variable in Neovim 0.9.  I call it Lazyman and include support for your `nvim` repository (called `Adib` in Lazyman)  as one of the "Personal" Neovim configurations installed and initialized by `lazyman`.

See https://github.com/doctorfree/nvim-lazyman for info on Lazyman.

I'm contacting the maintainers of the Lazyman supported Neovim configurations to seek any feedback on the description, installation, and initialization of their config in Lazyman. Please feel free to let me know what I'm doing wrong or how I could improve the incorporation of `Adib` in Lazyman. If you feel there is a need to modify the way `Adib` is used in Lazyman then open an issue at https://github.com/doctorfree/nvim-lazyman/issues

This isn't really an issue with Adib, it is just a heads up and request for feedback.

Adib is very cool. Thanks!

**Comment by adibhanna** [comment]
Thank you for adding my Neovim config to nvim-lazyman!
 
btw, Adib is actually my name :D it's funny when you:
```
This isn't really an issue with Adib, it is just a heads up and request for feedback.

Adib is very cool. Thanks!
```

**Comment by doctorfree** [comment]
@adibhanna Ha! Yes, I have no problem with you, Adib.

Adib is cool
